[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@diamond/=src/',
    '@diamond-script/=script/',
    '@diamond-test/=test/',
]
auto_detect_remappings = true
optimizer_runs = 100_000
ffi = true
via_ir = false

[fmt]
sort_imports = true
