[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@diamond/=src/',
    '@diamond-script/=script/',
    '@diamond-test/=test/',
]
optimizer_runs = 100_000
ffi = true

[fmt]
sort_imports = true
